name: Super-Linter
on: push
jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: conditional check
        if: 4>3 && 6>2
        run: echo "it works"
